import Head from "next/head";
import Image from "next/image";
import PropTypes from 'prop-types';
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Toppings from "@/components/Toppings";
import PizzaCrust from "@/components/PizzaCrust";


export default function Home() {
  return (
    <>
      <Head>
        <title>Pizza Bites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.backgroundImage}`}>
        <Header/>
        <SideBar/>
        <div className={`${styles.pizzaBox}`}>
          <PizzaCrust/>
          <Toppings className={`${styles.toppingsBox}`}/>
        </div>
      </main>
    </>
  );
}
